function randomFact() {
    const fact = [
        "You can add me to your server using my invite link?",
        "You can change my language by doing `/settings`?",
        "We are hiring staff members at [Support Server](https://discord.gg/QVnc6HxEBB)?",
        "You can get 4 free skipable cooldowns if you upvote Bridgify on [top.gg!](https://top.gg/bot/1193672589428654120)?",
        "Premium is $3 a month or $30 a year?",
        "This embed was orginally made by Foxems 💖?",
        "You can review Bridgify on [top.gg!](https://top.gg/bot/1193672589428654120)?",
        "We are on top.gg?",
        "Bridgify was orginally made by Zakleby but Steve Jobs took over?",
        "Bridgify made located in New York, United States with 💗?",
        "Bridgify started on 1/19/24?",
        "`/direct-partner` used to be `/partner`?",
        "Bridgify was made with ❤️ by StevieJobs and Zakleby?",
        "Bridgify is coded in JavaScript?",
        "We do Giveaways here and there on [Support Server](https://discord.gg/QVnc6HxEBB)?", 
        "Bridgify will have it's own partner soon, called `Bridgify Custodian`?",
        "Thank you for using Bridgify!",
        "Did you know that Bridgify can dance better than this cat: <a:CatJAM:1244009652002361374>?",
        "Waiting for a bump? Watch and let Bridgify handle the rest using the premium feature `/auto-bump`! <a:DiscordLoading:1244009948883456146>",
        "Our support team's reactions when you join the server: <:Joe_Wow:1223463255553478716>",
        "Bridgify is as essential to a server as Kyle The Shef is to Discord! <a:bot_discord:1223461710225084446>",
        "<a:timer8:1244014040213098507> Time's ticking! Use Bridgify's feature to schedule your next partnership!",
        "When Bridgify boosts your server's visibility: <a:Boost:1248382421246935173>",
        "Join the party at our support server with this cat: <a:Rainbow_Cat_Party:1248382475777081488> and make new friends!",
        "Feeling the heat of competition? Bridgify's got you covered!<a:Fuego1:1248382580731154443>!",
        "You can celebrate your server's growth with Bridgify and a festive <a:peepoTurkey:1248382792262484078>!",
        "Bridgify's is American as <a:peepoUSA:1248382880837533831> and as Turkish as a delightful cup of çay!",
        "You can unlock the secrets of server growth with Bridgify's algorithms! <a:sigma:1248383095443423242>",
        "Bridgify's got moves! Check out this Blob: <a:Smiledance:1248382303822938154> for a dance-off!",
        "Even this girl: <a:cutegirl:1248382373259776081> knows Bridgify is the best bot for Discord growth!",
        "When Bridgify updates, it's a whole celebration like Stewie Dancing: <a:Stewie_Dance:1248384580507930644>!",
        "Bridgify is as refreshing as feeling like this cat: <a:POVYouAreWater:1248384654491517040> on a hot day!",
        "Looking for a role in our community? Check out our [Support Server](https://discord.gg/QVnc6HxEBB) for the latest openings! <a:JobListings:1248384745101070386>",
        "Our community's vibe is more lively than Mr Skeleton: <a:dance_skeleton:1248384951540383788> at a dance party!",
        "Bridgify's response to server downtime: <a:Fook_You:1248385039322976430>? Not on our watch!",
        "Press this Button: <a:nuclear_launch_button:1248385601829339197> to launch your server's growth to the stratosphere with Bridgify!",
        "Bridgify's got the moves! Watch it groove with Stewie Dancing: <a:Stewie_Dance:1248384580507930644>!",
        "Stay hydrated while Bridgify does the work, just like Mr Cat: <a:POVYouAreWater:1248384654491517040>!",
        "Find your perfect server role with Bridgify's [Support Server](https://discord.gg/QVnc6HxEBB)! <a:JobListings:1248384745101070386>",
        "Bridgify keeps the party alive, more than Mr Skeleton: <a:dance_skeleton:1248384951540383788> on the dance floor!",
        "When servers clash, Bridgify steps in with a and responds with: <a:Fook_You:1248385039322976430> to downtime!",
        "Bridgify is the secret ingredient to a server's success, just like baklava to a Turkish feast!",
        "With Bridgify, your server's growth will be as unstoppable as a Turkish March!",
        "Bridgify brings servers together faster than a ferry across the Bosphorus!",
        "Let Bridgify be the bridge between your server and its potential, as strong as the Bosphorus Bridge!",
        "Bridgify's efficiency is unmatched, like a well-organized Turkish bazaar!",
        "Experience seamless server management with Bridgify, as smooth as Turkish coffee!",
        "Bridgify is the keystone of community building, much like the arches of a Turkish mosque!",
        "Bridgify's got your back, just like this strong arm: 💪!",
        "Bridgify is as reliable as the rising sun: 🌅!",
        "Bridgify's features are as cool as a snowflake: ❄️!",
        "Bridgify's got more moves than a dancing woman: 💃!",
        "Bridgify's as fast as a racing car: 🏎️!",
        "Bridgify's as smart as a graduation cap: 🎓!",
        "Bridgify's as helpful as a life preserver: ⛑️!",
        "Bridgify's as exciting as a roller coaster: 🎢!",
        "Bridgify's as creative as a painting: 🎨!",
        "Bridgify has a [YouTube Channel](https://youtube.com/@Bridgify-tutorials)?",
        "With Premium, you can setup your very own custom reminders for `/bump`, `/advertise` and `/partner-all-guilds`? <a:sigma:1248383095443423242>",
        "With Premium, you can make Bridgify ping a certain role to run `/bump`, `/advertise`, and `/partner-all-guilds` as your reminder! <a:sigma:1248383095443423242>",
        "Did you know that Baklava is from Turkey? <:baklava:1249094143116972065>",
        "Did you know that you can get Bridgify premium for free via by referrals? <a:sigma:1248383095443423242> Check out `/referral` for more information!",
        

    ];
    const index = Math.floor(Math.random() * fact.length);
    return fact[index]
}


module.exports = { randomFact }